Fix/negative rating
Whist-Team/Whist-Core pull request #227
Opened 2022-07-23 19:31 UTC by Segelzwerg

2022-07-23 19:53 UTC, Segelzwerg commented
Probably a bug in actions https://github.com/Whist-Team/actions/issues/4

2022-07-24 07:44 UTC, Segelzwerg commented
> Probably a bug in actions https://github.com/Whist-Team/actions/issues/4

Or user error 😉

2022-07-24 10:33 UTC, iTitus requested changes

2022-07-24 10:33 UTC, iTitus commented on whist_core/user/player.py
> +        Validates the rating. It must be zero or positiv.
```suggestion
        Validates the rating. It must be zero or positive.
```

2022-07-24 10:33 UTC, iTitus commented on whist_core/error/player_error.py
> +    Will be raised if a attempt to assign a negative rating to a player"""
Please fix the grammar.

2022-07-24 16:19 UTC, iTitus approved these changes

2022-07-24 16:20 UTC, merged